# CowMurder Configuration File

# General Settings
settings:
  # Enable/disable the plugin functionality
  enabled: true
  
  # Enable debug logging
  debug: false
  
  # Punishment type: DEATH, DAMAGE, LIGHTNING_ONLY
  punishment-type: DEATH
  
  # Amount of damage to deal if punishment-type is DAMAGE
  damage-amount: 10.0
  
  # Enable lightning effect when punishing
  lightning-effect: true
  
  # Enable custom death messages
  custom-death-messages: true

# Death Messages
# Use %player% as placeholder for player name
death-messages:
  - "%player% was moo-rdered for their bovine crimes"
  - "%player% faced divine bovine retribution"
  - "The cows fought back, and %player% lost"
  - "%player% learned the hard way not to mess with cows"
  - "A mysterious force struck down %player% for harming a cow"

# Scoreboard Settings
scoreboard:
  # Enable scoreboard tracking
  enabled: true
  
  # Track cow assaults (damage events)
  track-assaults: true
  
  # Track cow kills (death events)
  track-kills: true
  
  # Objective names
  assault-objective: "cowAssaults"
  kill-objective: "cowKills"
  
  # Display names
  assault-display: "Cow Assaults"
  kill-display: "Cow Kills"

# Permissions
permissions:
  # Permission to bypass punishment: cowmurder.bypass
  bypass-permission: "cowmurder.bypass"
  
  # Permission to use admin commands: cowmurder.admin
  admin-permission: "cowmurder.admin"
