name: CowMurder
version: ${version}
main: com.voidfemme.cowmurder.CowMurder
api-version: '1.21'
authors: [voidfemme]
description: A plugin that punishes players for harming cows
website: https://github.com/voidfemme/cowmurder

# Specify Mojang mappings for Paper 1.20.5+ compatibility
mappings: mojang

permissions:
  cowmurder.bypass:
    description: Allows players to harm cows without punishment
    default: op
  cowmurder.admin:
    description: Allows access to admin commands
    default: op

commands:
  cowmurder:
    description: Main CowMurder command
    usage: /cowmurder [reload|stats <player>]
    permission: cowmurder.admin
    aliases: [cm]
