name: CowMurder
version: ${version}
main: com.voidfemme.cowmurder.CowMurder
api-version: 1.21.4
description: A plugin that punishes players for harming cows
permissions:
  cowmurder.bypass:
    description: Allows players to harm cows without punishment
    default: op
  cowmurder.admin:
    description: Allows access to admin commands
    default: op
commands:
  cowmurder:
    description: Main CowMurder command
    usage: /cowmurder [reload|stats]
    permission: cowmurder.admin
